[project]
name = "artigo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pdfplumber>=0.11.9",
    "pillow>=12.2.0",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.3",
    "pymupdf>=1.27.2.2",
    "pytesseract>=0.3.13",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
]
